# Generated by Django 5.2.5 on 2025-08-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trace_minerals', 'data_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mineral',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
