# Generated by Django 2.1.7 on 2019-03-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trace_minerals', '0002_auto_20190319_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mineral',
            name='image_filename',
            field=models.FilePathField(verbose_name='trace_minerals/images/'),
        ),
    ]
