# Generated by Django 2.1.7 on 2019-03-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trace_minerals', '0003_auto_20190319_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mineral',
            name='image_filename',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
