# Generated by Django 2.1.7 on 2019-03-19 03:29

import json
import os

from django.conf import settings
from django.db import migrations


def load_data(apps, schema_editor):
    """
        custom data migration  logic that takes data from minerals.json

        creates mineral obj from data initial data is stored in
        :var: data the json is then iterated upon to process
        obj keys to proper format the data then is added as
        kwarg arguments for unsaved object mineral the object and
        kwarg are then appended to list: scrubbed_data which is passed
        as argument to minerals method bulk_create instantiating
        mineral objects and populating db

    """
    mineral = apps.get_model('trace_minerals', 'Mineral')
    filepath = os.path.join(settings.BASE_DIR, 'data/minerals.json')

    with open(filepath, mode='r') as file:
        data = json.load(file)
        scrubbed_data = []
        for obj in data:
            corrected_obj = {k.replace(' ', '_'): v for k, v in obj.items()}
            scrubbed_data.append(mineral(**corrected_obj))

        mineral.objects.bulk_create(scrubbed_data)
    file.close()


class Migration(migrations.Migration):

    dependencies = [
        ('trace_minerals', '0001_initial'),
        ]

    operations = [
        migrations.RunPython(load_data)
        ]
